id: I55A8487A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T15:16:22+00:00'
last_modified: '2022-06-07T22:31:35.537026+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4192
  title: ཁམས་སྤྲུལ་བསྟན་པའི་ཉི་མའི་གཏེར་བྱོན་དང་གསུང་ཐོར་བུ་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5B1A:
      image_group_id: I1PD96707
      title: ''
      total_pages: 482
      order: 1
      base_file: 5B1A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
