id: P004390
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4192
  title: ཁམས་སྤྲུལ་བསྟན་པའི་ཉི་མའི་གཏེར་བྱོན་དང་གསུང་ཐོར་བུ་སོགས
  author: ''
  volumes:
    3477f0449e7d417395b4b3c3db874575:
      image_group_id: I1PD96707
      title: ''
      volume_number: 1
      total_pages: 482
